# Generated by Django 3.0.2 on 2020-01-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.EmailField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
