# Generated by Django 3.0.2 on 2020-01-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default=True, max_length=40),
        ),
    ]
